import type { CommandItem } from "@/lib/command/types";
import { isNavigationVisible } from "@/lib/navigation/visibility";

function nav(
  partial: Omit<CommandItem, "section" | "keywords"> & {
    keywords?: string[];
  }
): CommandItem {
  return {
    section: "navigate",
    category: "گەشتکردن",
    keywords: partial.keywords || [partial.title],
    ...partial,
  };
}

function act(
  partial: Omit<CommandItem, "section" | "keywords"> & {
    keywords?: string[];
    category?: CommandItem["category"];
  }
): CommandItem {
  return {
    section: "action",
    category: partial.category || "دروستکردن",
    keywords: partial.keywords || [partial.title],
    ...partial,
  };
}

/** Navigate everywhere + create actions (Raycast / VS Code style). */
export const COMMAND_NAVIGATE: CommandItem[] = [
  nav({
    id: "nav-dashboard",
    title: "کردنەوەی داشبۆرد",
    subtitle: "داشبۆرد",
    description: "بڕۆ بۆ داشبۆردی سەرەکی",
    href: "/dashboard",
    keywords: ["dashboard", "داشبۆرد", "home", "open dashboard"],
    icon: "dashboard",
    shortcutId: "nav-1",
  }),
  nav({
    id: "nav-products",
    title: "کردنەوەی بەرهەمەکان",
    subtitle: "بەرهەمەکان · SKU · بارکۆد",
    description: "کاتالۆگی بەرهەمەکان ببینە",
    href: "/dashboard/products",
    keywords: ["products", "بەرهەم", "sku", "product", "open products", "prd"],
    icon: "product",
    shortcutId: "nav-2",
    contexts: ["/dashboard/products"],
  }),
  nav({
    id: "nav-sales",
    title: "کردنەوەی فرۆشتن",
    subtitle: "فرۆشتن",
    description: "لیستی فرۆشتن و پسوولەکان",
    href: "/dashboard/sales",
    keywords: ["sales", "فرۆشتن", "sale", "open sales"],
    icon: "sale",
    shortcutId: "nav-3",
    contexts: ["/dashboard/sales", "/dashboard/invoices"],
  }),
  nav({
    id: "nav-purchases",
    title: "کردنەوەی کڕین",
    subtitle: "کڕین",
    description: "داواکارییەکانی کڕین",
    href: "/dashboard/purchases",
    keywords: ["purchases", "کڕین", "purchase", "open purchases"],
    icon: "purchase",
    shortcutId: "nav-4",
    contexts: ["/dashboard/purchases"],
  }),
  nav({
    id: "nav-inventory",
    title: "کردنەوەی ئینڤێنتۆری",
    subtitle: "ئینڤێنتۆری",
    description: "پوختەی کۆگا",
    href: "/dashboard/inventory",
    keywords: ["inventory", "ئینڤێنتۆری", "stock", "open inventory"],
    icon: "inventory",
    shortcutId: "nav-5",
    contexts: ["/dashboard/inventory"],
  }),
  nav({
    id: "nav-customers",
    title: "کردنەوەی کڕیارەکان",
    subtitle: "کڕیارەکان",
    description: "لیستی کڕیارەکان",
    href: "/dashboard/customers",
    keywords: ["customers", "کڕیار", "customer", "open customers"],
    icon: "customer",
    shortcutId: "nav-6",
    contexts: ["/dashboard/customers"],
  }),
  nav({
    id: "nav-suppliers",
    title: "کردنەوەی دابینکەران",
    subtitle: "دابینکەران",
    description: "لیستی دابینکەران",
    href: "/dashboard/suppliers",
    keywords: ["suppliers", "دابینکەر", "supplier", "open suppliers"],
    icon: "supplier",
    shortcutId: "nav-7",
    contexts: ["/dashboard/suppliers"],
  }),
  nav({
    id: "nav-reports",
    title: "کردنەوەی ڕاپۆرتەکان",
    subtitle: "ڕاپۆرتەکان",
    description: "ڕاپۆرتەکانی کار",
    href: "/dashboard/reports",
    keywords: ["reports", "ڕاپۆرت", "report", "open reports"],
    icon: "reports",
    shortcutId: "nav-8",
    contexts: ["/dashboard/reports"],
  }),
  nav({
    id: "nav-settings",
    title: "کردنەوەی ڕێکخستنەکان",
    subtitle: "ڕێکخستنەکان",
    description: "ڕێکخستنەکانی کۆمپانیا و سیستەم",
    href: "/dashboard/settings",
    keywords: ["settings", "ڕێکخستن", "سێتینگ", "open settings"],
    icon: "settings",
    shortcutId: "nav-9",
    contexts: ["/dashboard/settings"],
  }),
  nav({
    id: "nav-warehouses",
    title: "کردنەوەی کۆگاکان",
    subtitle: "کۆگاکان",
    description: "شوێنەکانی کۆگا",
    href: "/dashboard/werehouse",
    keywords: ["warehouse", "warehouses", "کۆگا", "werehouse", "open warehouses"],
    icon: "warehouse",
    category: "کۆگا",
    contexts: ["/dashboard/werehouse"],
  }),
  nav({
    id: "nav-employees",
    title: "کردنەوەی کارمەندان",
    subtitle: "کارمەندان",
    description: "کارمەندان و کارگێڕی",
    href: "/dashboard/employees",
    keywords: ["employees", "کارمەند", "employee", "hr", "staff", "open employees"],
    icon: "employee",
    contexts: ["/dashboard/employees"],
  }),
  nav({
    id: "nav-analytics",
    title: "کردنەوەی شیکاری",
    subtitle: "شیکاری",
    description: "هێڵکاری و پێوەرەکان",
    href: "/dashboard/analytics",
    keywords: ["analytics", "شیکاری", "kpi", "open analytics"],
    icon: "reports",
    category: "شیکاری",
    contexts: ["/dashboard/analytics"],
  }),
  nav({
    id: "nav-notifications",
    title: "کردنەوەی ئاگادارییەکان",
    subtitle: "ئاگادارییەکان",
    description: "ناوەندی ئاگاداری",
    href: "/dashboard/notifications",
    keywords: ["notifications", "ئاگاداری", "alert", "open notifications"],
    icon: "notification",
  }),
  nav({
    id: "nav-calculator",
    title: "کردنەوەی ژمێرەر",
    subtitle: "ژمێرەر",
    description: "ژمێرەری ناوخۆیی",
    href: "/dashboard/calculator",
    keywords: ["calculator", "ژمێرەر", "calc", "open calculator"],
    icon: "search",
  }),
  nav({
    id: "nav-invoices",
    title: "کردنەوەی پسوولەکان",
    subtitle: "پسوولەکان",
    description: "ئەرشیفی پسوولەکان",
    href: "/dashboard/invoices",
    keywords: ["invoices", "پسوولە", "invoice", "open invoices"],
    icon: "invoice",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  nav({
    id: "nav-barcode",
    title: "کردنەوەی بارکۆد",
    subtitle: "سکانەر · چاپ",
    description: "سەکۆی بارکۆد",
    href: "/dashboard/barcode",
    keywords: ["barcode", "بارکۆد", "scan", "سکان"],
    icon: "barcode",
    contexts: ["/dashboard/barcode", "/dashboard/products"],
  }),
  nav({
    id: "nav-units",
    title: "کردنەوەی یەکەکان",
    subtitle: "یەکەکان",
    href: "/dashboard/units",
    keywords: ["units", "یەکە", "unit"],
    icon: "unit",
  }),
  nav({
    id: "nav-activity",
    title: "کردنەوەی تێمڵاینی چالاکی",
    subtitle: "مێژووی سیستەم",
    href: "/dashboard/activity",
    keywords: [
      "activity",
      "timeline",
      "audit",
      "log",
      "چاودێری",
      "تۆمار",
      "history",
    ],
    icon: "history",
    category: "سیستەم",
  }),
  nav({
    id: "nav-audit",
    title: "کردنەوەی تۆماری چاودێری",
    subtitle: "تۆماری چاودێری",
    href: "/dashboard/audit-log",
    keywords: ["audit", "log", "چاودێری", "تۆمار"],
    icon: "reports",
    category: "سیستەم",
  }),
  nav({
    id: "nav-ai-assistant",
    title: "کردنەوەی یاریدەدەری زیرەک",
    subtitle: "تێڕوانین · ئاگاداری · خۆکارکردن",
    href: "/dashboard/ai-assistant",
    keywords: [
      "ai",
      "assistant",
      "smart",
      "automation",
      "insights",
      "recommendations",
      "alerts",
      "یاریدەدەر",
      "ژیری",
    ],
    icon: "search",
    category: "سیستەم",
    shortcutId: "ai-assistant",
  }),
  nav({
    id: "nav-recent",
    title: "کردنەوەی دوایین بینراوەکان",
    subtitle: "مێژوو",
    href: "/dashboard/recent",
    keywords: ["recent", "history", "viewed", "دوایین"],
    icon: "history",
  }),
  nav({
    id: "nav-drafts",
    title: "کردنەوەی ناوەندی ڕەشنووس",
    subtitle: "ڕەشنووس · بەردەوامبوون",
    description: "بەڕێوەبردن و بەردەوامبوون لە ڕەشنووسە تەواونەبووەکان",
    href: "/dashboard/drafts",
    keywords: ["draft", "drafts", "recovery", "restore draft", "ڕەشنووس", "resume"],
    icon: "search",
    category: "سیستەم",
  }),
  nav({
    id: "nav-recycle-bin",
    title: "کردنەوەی سەبەتەی زبڵ",
    subtitle: "سڕاوە · گەڕاندنەوە",
    description: "گەڕاندنەوە یان سڕینەوەی هەمیشەیی تۆمارە سڕاوەکان",
    href: "/dashboard/recycle-bin",
    keywords: [
      "recycle",
      "bin",
      "trash",
      "deleted",
      "restore",
      "purge",
      "سڕاوە",
      "گەڕاندنەوە",
    ],
    icon: "search",
    category: "سیستەم",
  }),
  nav({
    id: "nav-bulk",
    title: "کردنەوەی کردارە کۆمەڵایەتییەکان",
    subtitle: "هەڵبژاردنی فرە · کارە کۆمەڵەکان",
    description: "پێداچوونەوەی کارە کۆمەڵەکان، پێشکەوتن و پاشگەزبوونەوە",
    href: "/dashboard/bulk",
    keywords: ["bulk", "batch", "multi", "select", "کۆمەڵ"],
    icon: "search",
    category: "سیستەم",
  }),
  nav({
    id: "nav-recovery",
    title: "کردنەوەی ناوەندی گەڕاندنەوە",
    subtitle: "دانیشتنەکان",
    description: "گەڕاندنەوەی دانیشتنی تێکچوو",
    href: "/dashboard/recovery",
    keywords: ["session", "recovery", "crash"],
    icon: "search",
    category: "سیستەم",
  }),
  nav({
    id: "nav-adjustments",
    title: "کردنەوەی ڕێکخستنی کۆگا",
    href: "/dashboard/inventory/adjustments",
    keywords: ["adjustment", "ڕێکخستن", "stock"],
    icon: "inventory",
    category: "ئینڤێنتۆری",
    contexts: ["/dashboard/inventory"],
  }),
  nav({
    id: "nav-transfers",
    title: "کردنەوەی گواستنەوەی کۆگا",
    href: "/dashboard/inventory/transfers",
    keywords: ["transfer", "گواستنەوە"],
    icon: "inventory",
    category: "ئینڤێنتۆری",
    contexts: ["/dashboard/inventory"],
  }),
];

export const COMMAND_ACTIONS: CommandItem[] = [
  act({
    id: "act-new-product",
    title: "دروستکردنی بەرهەم",
    subtitle: "بەرهەمی نوێ",
    description: "تۆماری بەرهەمێکی نوێ دروست بکە",
    href: "/dashboard/products/new",
    keywords: ["new product", "create product", "add product", "prd", "بەرهەمی نوێ"],
    icon: "plus",
    shortcutId: "create-new",
    contexts: ["/dashboard/products"],
  }),
  act({
    id: "act-new-sale",
    title: "دروستکردنی فرۆشتن",
    subtitle: "فرۆشتنی نوێ",
    description: "فرۆشتنێکی نوێ دەست پێ بکە",
    href: "/dashboard/sales/new",
    keywords: ["new sale", "create sale", "create new sale", "فرۆشتنی نوێ"],
    icon: "plus",
    category: "فرۆشتن",
    contexts: ["/dashboard/sales", "/dashboard/invoices"],
  }),
  act({
    id: "act-new-purchase",
    title: "دروستکردنی کڕین",
    subtitle: "کڕینی نوێ",
    href: "/dashboard/purchases/new",
    keywords: ["new purchase", "create purchase", "کڕینی نوێ"],
    icon: "plus",
    category: "کڕین",
    contexts: ["/dashboard/purchases"],
  }),
  act({
    id: "act-new-invoice",
    title: "دروستکردنی پسوولە",
    subtitle: "لە ڕێگەی فرۆشتنی نوێ",
    description: "پسوولەی فرۆشتن دروست بکە",
    href: "/dashboard/sales/new",
    keywords: ["create invoice", "new invoice", "پسوولە"],
    icon: "plus",
    category: "فرۆشتن",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  act({
    id: "act-new-customer",
    title: "دروستکردنی کڕیار",
    subtitle: "کڕیاری نوێ",
    href: "/dashboard/customers/new",
    keywords: ["new customer", "create customer", "کڕیاری نوێ"],
    icon: "plus",
    contexts: ["/dashboard/customers"],
  }),
  act({
    id: "act-new-supplier",
    title: "دروستکردنی دابینکەر",
    subtitle: "دابینکەری نوێ",
    href: "/dashboard/suppliers/new",
    keywords: ["new supplier", "create supplier", "دابینکەری نوێ"],
    icon: "plus",
    contexts: ["/dashboard/suppliers"],
  }),
  act({
    id: "act-new-employee",
    title: "دروستکردنی کارمەند",
    href: "/dashboard/employees/new",
    keywords: ["new employee", "create employee"],
    icon: "plus",
    contexts: ["/dashboard/employees"],
  }),
  act({
    id: "act-new-warehouse",
    title: "دروستکردنی کۆگا",
    href: "/dashboard/werehouse/new",
    keywords: ["new warehouse", "create warehouse"],
    icon: "plus",
    category: "کۆگا",
    contexts: ["/dashboard/werehouse"],
  }),
  act({
    id: "act-new-unit",
    title: "دروستکردنی یەکە",
    href: "/dashboard/units/new",
    keywords: ["new unit", "create unit"],
    icon: "plus",
  }),
  act({
    id: "act-print-invoice",
    title: "چاپکردنی پسوولە",
    description: "پسوولەی ئێستا چاپ بکە یان پسوولەکان بکەرەوە",
    href: "/dashboard/invoices",
    actionId: "print",
    keywords: ["print invoice", "چاپ", "print"],
    icon: "invoice",
    category: "فرۆشتن",
    shortcutId: "print",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  act({
    id: "act-print-barcode",
    title: "چاپکردنی بارکۆد",
    description: "سەکۆی چاپکردنی بارکۆد بکەرەوە",
    href: "/dashboard/barcode",
    keywords: ["print barcode", "بارکۆد", "barcode"],
    icon: "barcode",
    category: "ئینڤێنتۆری",
    contexts: ["/dashboard/products", "/dashboard/barcode"],
  }),
  act({
    id: "act-export-report",
    title: "هەناردەکردنی ڕاپۆرت",
    description: "ڕاپۆرتەکان بکەرەوە بۆ هەناردەی PDF / Excel",
    href: "/dashboard/reports",
    keywords: ["export report", "export", "pdf", "excel"],
    icon: "reports",
    category: "ڕاپۆرتەکان",
    contexts: ["/dashboard/reports"],
  }),
  act({
    id: "act-backup",
    title: "پاشەکەوتی بنکەدراوە",
    subtitle: "لە ڕێگەی ڕێکخستنەکان",
    description: "ڕێکخستنەکان بکەرەوە بۆ ئامرازەکانی پاشەکەوت",
    href: "/dashboard/settings",
    keywords: ["backup", "database", "backup database"],
    icon: "settings",
    category: "سیستەم",
  }),
  act({
    id: "act-refresh-dashboard",
    title: "نوێکردنەوەی داشبۆرد",
    description: "داتای مۆدیوولی ئێستا نوێ بکەرەوە",
    actionId: "refresh",
    keywords: ["refresh", "reload", "refresh dashboard"],
    icon: "dashboard",
    category: "سیستەم",
    shortcutId: "refresh",
  }),
  act({
    id: "act-duplicate",
    title: "دووبارەکردنەوەی تۆمار",
    description: "تۆماری ئێستا دووبارە بکەرەوە کاتێک پشتگیری دەکرێت",
    actionId: "duplicate-record",
    keywords: ["duplicate", "clone", "copy record"],
    icon: "plus",
    category: "Editing",
    shortcutId: "duplicate",
  }),
  act({
    id: "act-manual-save",
    title: "پاشەکەوتی دەستی",
    description: "فۆرمی ئێستا پاشەکەوت بکە کاتێک پشتگیری دەکرێت",
    actionId: "manual-save",
    keywords: ["save", "manual save"],
    icon: "settings",
    category: "Editing",
    shortcutId: "manual-save",
  }),
  act({
    id: "act-page-search",
    title: "گەڕان لە پەڕەی ئێستا",
    actionId: "focus-page-search",
    keywords: ["find", "search page", "ctrl f"],
    icon: "search",
    category: "Searching",
    shortcutId: "page-search",
  }),
  act({
    id: "act-cheat-sheet",
    title: "لیستی قەدبڕەکان",
    description: "هەموو قەدبڕەکان پیشان بدە",
    actionId: "open-cheat-sheet",
    keywords: ["shortcuts", "cheat sheet", "keyboard"],
    icon: "search",
    category: "سیستەم",
    shortcutId: "cheat-sheet",
  }),
  act({
    id: "act-barcode",
    title: "کردنەوەی سکانەری بارکۆد",
    href: "/dashboard/barcode",
    keywords: ["scan", "سکان", "barcode"],
    icon: "barcode",
    category: "ئینڤێنتۆری",
  }),
  act({
    id: "act-theme",
    title: "گۆڕینی ڕووکار",
    subtitle: "ڕووناک / تاریک",
    actionId: "toggle-theme",
    keywords: ["theme", "dark", "light", "ڕووکار"],
    icon: "theme",
    category: "سیستەم",
  }),
  act({
    id: "act-logout",
    title: "چوونەدەرەوە",
    description: "لە REK ERP بچۆ دەرەوە",
    actionId: "logout",
    keywords: ["logout", "sign out", "چوونەدەرەوە"],
    icon: "settings",
    category: "سیستەم",
  }),
];

export const ALL_STATIC_COMMANDS: CommandItem[] = [
  ...COMMAND_ACTIONS,
  ...COMMAND_NAVIGATE.filter(
    (item) => !item.href || isNavigationVisible(item.href)
  ),
];

export function commandsForPath(pathname: string): CommandItem[] {
  return ALL_STATIC_COMMANDS.filter(
    (c) =>
      c.contexts?.some(
        (ctx) => pathname === ctx || pathname.startsWith(`${ctx}/`)
      )
  );
}

export function enrichCommandShortcuts(
  items: CommandItem[],
  labelFor: (shortcutId: string) => string | undefined
): CommandItem[] {
  return items.map((c) => ({
    ...c,
    shortcut: c.shortcutId ? labelFor(c.shortcutId) || c.shortcut : c.shortcut,
  }));
}
