import type { CommandItem } from "@/lib/command/types";

function nav(
  partial: Omit<CommandItem, "section" | "keywords"> & {
    keywords?: string[];
  }
): CommandItem {
  return {
    section: "navigate",
    category: "Navigation",
    keywords: partial.keywords || [partial.title],
    ...partial,
  };
}

function act(
  partial: Omit<CommandItem, "section" | "keywords"> & {
    keywords?: string[];
    category?: CommandItem["category"];
  }
): CommandItem {
  return {
    section: "action",
    category: partial.category || "Creation",
    keywords: partial.keywords || [partial.title],
    ...partial,
  };
}

/** Navigate everywhere + create actions (Raycast / VS Code style). */
export const COMMAND_NAVIGATE: CommandItem[] = [
  nav({
    id: "nav-dashboard",
    title: "Open Dashboard",
    subtitle: "داشبۆرد",
    description: "Go to the main dashboard workspace",
    href: "/dashboard",
    keywords: ["dashboard", "داشبۆرد", "home", "open dashboard"],
    icon: "dashboard",
    shortcutId: "nav-1",
  }),
  nav({
    id: "nav-products",
    title: "Open Products",
    subtitle: "Products · SKU · Barcode",
    description: "Browse product catalog",
    href: "/dashboard/products",
    keywords: ["products", "بەرهەم", "sku", "product", "open products", "prd"],
    icon: "product",
    shortcutId: "nav-2",
    contexts: ["/dashboard/products"],
  }),
  nav({
    id: "nav-sales",
    title: "Open Sales",
    subtitle: "Sales",
    description: "Sales list and invoices",
    href: "/dashboard/sales",
    keywords: ["sales", "فرۆشتن", "sale", "open sales"],
    icon: "sale",
    shortcutId: "nav-3",
    contexts: ["/dashboard/sales", "/dashboard/invoices"],
  }),
  nav({
    id: "nav-purchases",
    title: "Open Purchases",
    subtitle: "Purchases",
    description: "Purchase orders",
    href: "/dashboard/purchases",
    keywords: ["purchases", "کڕین", "purchase", "open purchases"],
    icon: "purchase",
    shortcutId: "nav-4",
    contexts: ["/dashboard/purchases"],
  }),
  nav({
    id: "nav-inventory",
    title: "Open Inventory",
    subtitle: "Inventory",
    description: "Stock overview",
    href: "/dashboard/inventory",
    keywords: ["inventory", "ئینڤێنتۆری", "stock", "open inventory"],
    icon: "inventory",
    shortcutId: "nav-5",
    contexts: ["/dashboard/inventory"],
  }),
  nav({
    id: "nav-customers",
    title: "Open Customers",
    subtitle: "Customers",
    description: "Customer directory",
    href: "/dashboard/customers",
    keywords: ["customers", "کڕیار", "customer", "open customers"],
    icon: "customer",
    shortcutId: "nav-6",
    contexts: ["/dashboard/customers"],
  }),
  nav({
    id: "nav-suppliers",
    title: "Open Suppliers",
    subtitle: "Suppliers",
    description: "Supplier directory",
    href: "/dashboard/suppliers",
    keywords: ["suppliers", "دابینکەر", "supplier", "open suppliers"],
    icon: "supplier",
    shortcutId: "nav-7",
    contexts: ["/dashboard/suppliers"],
  }),
  nav({
    id: "nav-reports",
    title: "Open Reports",
    subtitle: "Reports",
    description: "Business reports",
    href: "/dashboard/reports",
    keywords: ["reports", "ڕاپۆرت", "report", "open reports"],
    icon: "reports",
    shortcutId: "nav-8",
    contexts: ["/dashboard/reports"],
  }),
  nav({
    id: "nav-settings",
    title: "Open Settings",
    subtitle: "Settings",
    description: "Company and system settings",
    href: "/dashboard/settings",
    keywords: ["settings", "ڕێکخستن", "سێتینگ", "open settings"],
    icon: "settings",
    shortcutId: "nav-9",
    contexts: ["/dashboard/settings"],
  }),
  nav({
    id: "nav-warehouses",
    title: "Open Warehouses",
    subtitle: "Warehouses",
    description: "Warehouse locations",
    href: "/dashboard/werehouse",
    keywords: ["warehouse", "warehouses", "کۆگا", "werehouse", "open warehouses"],
    icon: "warehouse",
    category: "Warehouse",
    contexts: ["/dashboard/werehouse"],
  }),
  nav({
    id: "nav-employees",
    title: "Open Employees",
    subtitle: "Employees",
    description: "HR and staff",
    href: "/dashboard/employees",
    keywords: ["employees", "کارمەند", "employee", "hr", "staff", "open employees"],
    icon: "employee",
    contexts: ["/dashboard/employees"],
  }),
  nav({
    id: "nav-analytics",
    title: "Open Analytics",
    subtitle: "Analytics",
    description: "Charts and KPIs",
    href: "/dashboard/analytics",
    keywords: ["analytics", "شیکاری", "kpi", "open analytics"],
    icon: "reports",
    category: "Analytics",
    contexts: ["/dashboard/analytics"],
  }),
  nav({
    id: "nav-notifications",
    title: "Open Notifications",
    subtitle: "Notifications",
    description: "Notification center",
    href: "/dashboard/notifications",
    keywords: ["notifications", "ئاگاداری", "alert", "open notifications"],
    icon: "notification",
  }),
  nav({
    id: "nav-calculator",
    title: "Open Calculator",
    subtitle: "Calculator",
    description: "Built-in calculator",
    href: "/dashboard/calculator",
    keywords: ["calculator", "ژمێرەر", "calc", "open calculator"],
    icon: "search",
  }),
  nav({
    id: "nav-invoices",
    title: "Open Invoices",
    subtitle: "Invoices",
    description: "Invoice archive",
    href: "/dashboard/invoices",
    keywords: ["invoices", "پسوولە", "invoice", "open invoices"],
    icon: "invoice",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  nav({
    id: "nav-barcode",
    title: "Open Barcode",
    subtitle: "Scanner · Print",
    description: "Barcode workbench",
    href: "/dashboard/barcode",
    keywords: ["barcode", "بارکۆد", "scan", "سکان"],
    icon: "barcode",
    contexts: ["/dashboard/barcode", "/dashboard/products"],
  }),
  nav({
    id: "nav-units",
    title: "Open Units",
    subtitle: "Units",
    href: "/dashboard/units",
    keywords: ["units", "یەکە", "unit"],
    icon: "unit",
  }),
  nav({
    id: "nav-activity",
    title: "Open Activity Timeline",
    subtitle: "Enterprise history",
    href: "/dashboard/activity",
    keywords: [
      "activity",
      "timeline",
      "audit",
      "log",
      "چاودێری",
      "تۆمار",
      "history",
    ],
    icon: "history",
    category: "System",
  }),
  nav({
    id: "nav-audit",
    title: "Open Audit Log",
    subtitle: "Audit Log",
    href: "/dashboard/audit-log",
    keywords: ["audit", "log", "چاودێری", "تۆمار"],
    icon: "reports",
    category: "System",
  }),
  nav({
    id: "nav-version-history",
    title: "Open Version History",
    subtitle: "Compare · Restore versions",
    href: "/dashboard/version-history",
    keywords: [
      "version",
      "history",
      "compare",
      "restore",
      "وەشان",
      "مێژوو",
      "diff",
    ],
    icon: "history",
    category: "System",
  }),
  nav({
    id: "nav-ai-assistant",
    title: "Open AI Assistant",
    subtitle: "Insights · Alerts · Automation",
    href: "/dashboard/ai-assistant",
    keywords: [
      "ai",
      "assistant",
      "smart",
      "automation",
      "insights",
      "recommendations",
      "alerts",
      "یاریدەدەر",
      "ژیری",
    ],
    icon: "search",
    category: "System",
    shortcutId: "ai-assistant",
  }),
  nav({
    id: "nav-recent",
    title: "Open Recently Viewed",
    subtitle: "History",
    href: "/dashboard/recent",
    keywords: ["recent", "history", "viewed", "دوایین"],
    icon: "history",
  }),
  nav({
    id: "nav-drafts",
    title: "Open Draft Center",
    subtitle: "Drafts · Resume",
    description: "Manage and resume unfinished drafts",
    href: "/dashboard/drafts",
    keywords: ["draft", "drafts", "recovery", "restore draft", "ڕەشنووس", "resume"],
    icon: "search",
    category: "System",
  }),
  nav({
    id: "nav-recycle-bin",
    title: "Open Recycle Bin",
    subtitle: "Deleted · Restore",
    description: "Restore or permanently delete soft-deleted records",
    href: "/dashboard/recycle-bin",
    keywords: [
      "recycle",
      "bin",
      "trash",
      "deleted",
      "restore",
      "purge",
      "سڕاوە",
      "گەڕاندنەوە",
    ],
    icon: "search",
    category: "System",
  }),
  nav({
    id: "nav-bulk",
    title: "Open Bulk Operations",
    subtitle: "Multi-select · Batch jobs",
    description: "Review bulk jobs, progress, and undo",
    href: "/dashboard/bulk",
    keywords: ["bulk", "batch", "multi", "select", "کۆمەڵ"],
    icon: "search",
    category: "System",
  }),
  nav({
    id: "nav-numbering",
    title: "Open Auto Numbering",
    subtitle: "Document numbers · SKU",
    description: "Configure smart auto numbering formats",
    href: "/dashboard/settings/numbering",
    keywords: ["numbering", "sequence", "sku", "invoice", "ژمارە"],
    icon: "settings",
    category: "System",
  }),
  nav({
    id: "nav-recovery",
    title: "Open Recovery Center",
    subtitle: "Sessions",
    description: "Session crash recovery",
    href: "/dashboard/recovery",
    keywords: ["session", "recovery", "crash"],
    icon: "search",
    category: "System",
  }),
  nav({
    id: "nav-adjustments",
    title: "Open Stock Adjustments",
    href: "/dashboard/inventory/adjustments",
    keywords: ["adjustment", "ڕێکخستن", "stock"],
    icon: "inventory",
    category: "Inventory",
    contexts: ["/dashboard/inventory"],
  }),
  nav({
    id: "nav-transfers",
    title: "Open Stock Transfers",
    href: "/dashboard/inventory/transfers",
    keywords: ["transfer", "گواستنەوە"],
    icon: "inventory",
    category: "Inventory",
    contexts: ["/dashboard/inventory"],
  }),
];

export const COMMAND_ACTIONS: CommandItem[] = [
  act({
    id: "act-new-product",
    title: "Create Product",
    subtitle: "بەرهەمی نوێ",
    description: "Create a new product record",
    href: "/dashboard/products/new",
    keywords: ["new product", "create product", "add product", "prd", "بەرهەمی نوێ"],
    icon: "plus",
    shortcutId: "create-new",
    contexts: ["/dashboard/products"],
  }),
  act({
    id: "act-new-sale",
    title: "Create Sale",
    subtitle: "فرۆشتنی نوێ",
    description: "Start a new sale",
    href: "/dashboard/sales/new",
    keywords: ["new sale", "create sale", "create new sale", "فرۆشتنی نوێ"],
    icon: "plus",
    category: "Sales",
    contexts: ["/dashboard/sales", "/dashboard/invoices"],
  }),
  act({
    id: "act-new-purchase",
    title: "Create Purchase",
    subtitle: "کڕینی نوێ",
    href: "/dashboard/purchases/new",
    keywords: ["new purchase", "create purchase", "کڕینی نوێ"],
    icon: "plus",
    category: "Purchases",
    contexts: ["/dashboard/purchases"],
  }),
  act({
    id: "act-new-invoice",
    title: "Create Invoice",
    subtitle: "Via new sale",
    description: "Create a sale invoice",
    href: "/dashboard/sales/new",
    keywords: ["create invoice", "new invoice", "پسوولە"],
    icon: "plus",
    category: "Sales",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  act({
    id: "act-new-customer",
    title: "Create Customer",
    subtitle: "کڕیاری نوێ",
    href: "/dashboard/customers/new",
    keywords: ["new customer", "create customer", "کڕیاری نوێ"],
    icon: "plus",
    contexts: ["/dashboard/customers"],
  }),
  act({
    id: "act-new-supplier",
    title: "Create Supplier",
    subtitle: "دابینکەری نوێ",
    href: "/dashboard/suppliers/new",
    keywords: ["new supplier", "create supplier", "دابینکەری نوێ"],
    icon: "plus",
    contexts: ["/dashboard/suppliers"],
  }),
  act({
    id: "act-new-employee",
    title: "Create Employee",
    href: "/dashboard/employees/new",
    keywords: ["new employee", "create employee"],
    icon: "plus",
    contexts: ["/dashboard/employees"],
  }),
  act({
    id: "act-new-warehouse",
    title: "Create Warehouse",
    href: "/dashboard/werehouse/new",
    keywords: ["new warehouse", "create warehouse"],
    icon: "plus",
    category: "Warehouse",
    contexts: ["/dashboard/werehouse"],
  }),
  act({
    id: "act-new-unit",
    title: "Create Unit",
    href: "/dashboard/units/new",
    keywords: ["new unit", "create unit"],
    icon: "plus",
  }),
  act({
    id: "act-print-invoice",
    title: "Print Invoice",
    description: "Print current invoice or open invoices",
    href: "/dashboard/invoices",
    actionId: "print",
    keywords: ["print invoice", "چاپ", "print"],
    icon: "invoice",
    category: "Sales",
    shortcutId: "print",
    contexts: ["/dashboard/invoices", "/dashboard/sales"],
  }),
  act({
    id: "act-print-barcode",
    title: "Print Barcode",
    description: "Open barcode print workbench",
    href: "/dashboard/barcode",
    keywords: ["print barcode", "بارکۆد", "barcode"],
    icon: "barcode",
    category: "Inventory",
    contexts: ["/dashboard/products", "/dashboard/barcode"],
  }),
  act({
    id: "act-export-report",
    title: "Export Report",
    description: "Open reports for PDF / Excel export",
    href: "/dashboard/reports",
    keywords: ["export report", "export", "pdf", "excel"],
    icon: "reports",
    category: "Reports",
    contexts: ["/dashboard/reports"],
  }),
  act({
    id: "act-backup",
    title: "Backup Database",
    subtitle: "Via settings",
    description: "Open settings for backup-related tools",
    href: "/dashboard/settings",
    keywords: ["backup", "database", "backup database"],
    icon: "settings",
    category: "System",
  }),
  act({
    id: "act-refresh-dashboard",
    title: "Refresh Dashboard",
    description: "Refresh current module data",
    actionId: "refresh",
    keywords: ["refresh", "reload", "refresh dashboard"],
    icon: "dashboard",
    category: "System",
    shortcutId: "refresh",
  }),
  act({
    id: "act-duplicate",
    title: "Duplicate Record",
    description: "Duplicate current record when supported",
    actionId: "duplicate-record",
    keywords: ["duplicate", "clone", "copy record"],
    icon: "plus",
    category: "Editing",
    shortcutId: "duplicate",
  }),
  act({
    id: "act-manual-save",
    title: "Manual Save",
    description: "Save current form when supported",
    actionId: "manual-save",
    keywords: ["save", "manual save"],
    icon: "settings",
    category: "Editing",
    shortcutId: "manual-save",
  }),
  act({
    id: "act-page-search",
    title: "Search Current Page",
    actionId: "focus-page-search",
    keywords: ["find", "search page", "ctrl f"],
    icon: "search",
    category: "Searching",
    shortcutId: "page-search",
  }),
  act({
    id: "act-cheat-sheet",
    title: "Keyboard Cheat Sheet",
    description: "Show all shortcuts",
    actionId: "open-cheat-sheet",
    keywords: ["shortcuts", "cheat sheet", "keyboard"],
    icon: "search",
    category: "System",
    shortcutId: "cheat-sheet",
  }),
  act({
    id: "act-barcode",
    title: "Open Barcode Scanner",
    href: "/dashboard/barcode",
    keywords: ["scan", "سکان", "barcode"],
    icon: "barcode",
    category: "Inventory",
  }),
  act({
    id: "act-theme",
    title: "Toggle Theme",
    subtitle: "Light / Dark",
    actionId: "toggle-theme",
    keywords: ["theme", "dark", "light", "ڕووکار"],
    icon: "theme",
    category: "System",
  }),
  act({
    id: "act-logout",
    title: "Logout",
    description: "Sign out of REK ERP",
    actionId: "logout",
    keywords: ["logout", "sign out", "چوونەدەرەوە"],
    icon: "settings",
    category: "System",
  }),
];

export const ALL_STATIC_COMMANDS: CommandItem[] = [
  ...COMMAND_ACTIONS,
  ...COMMAND_NAVIGATE,
];

export function commandsForPath(pathname: string): CommandItem[] {
  return ALL_STATIC_COMMANDS.filter(
    (c) =>
      c.contexts?.some(
        (ctx) => pathname === ctx || pathname.startsWith(`${ctx}/`)
      )
  );
}

export function enrichCommandShortcuts(
  items: CommandItem[],
  labelFor: (shortcutId: string) => string | undefined
): CommandItem[] {
  return items.map((c) => ({
    ...c,
    shortcut: c.shortcutId ? labelFor(c.shortcutId) || c.shortcut : c.shortcut,
  }));
}
