"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { KeyRound, LoaderCircle } from "lucide-react";

export default function SuperAdminPasswordForm() {
  const router = useRouter(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (password !== confirm) { setMessage("وشە نهێنییەکان یەکسان نین."); return; } setBusy(true); setMessage(null); try { const res = await fetch("/api/admin/auth/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const body = await res.json(); if (!res.ok) throw new Error(body.message || "گۆڕینی وشەی نهێنی سەرنەکەوت."); router.replace("/admin"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "گۆڕینی وشەی نهێنی سەرنەکەوت."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="w-full max-w-md rounded-[28px] border border-primary/20 bg-card p-6 shadow-[0_24px_70px_var(--shadow-brand)] sm:p-8" dir="rtl"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/12 text-primary"><KeyRound size={24} /></div><h1 className="mt-5 text-3xl font-black">گۆڕینی وشەی نهێنی</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">بۆ یەکەم چوونەژوورەوە، پێویستە وشەی نهێنییەکی نوێ و بەهێز دابنێیت.</p><label className="mt-6 block text-sm font-black">وشەی نهێنیی نوێ<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={16} className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-left outline-none focus:border-primary/60" dir="ltr" /></label><label className="mt-4 block text-sm font-black">دووبارەکردنەوە<input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required minLength={16} className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-left outline-none focus:border-primary/60" dir="ltr" /></label>{message ? <p role="status" className="mt-4 rounded-xl bg-destructive/10 px-3 py-2 text-sm text-destructive">{message}</p> : null}<button disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary font-black text-primary-foreground disabled:opacity-60">{busy ? <LoaderCircle className="animate-spin" size={18} /> : <KeyRound size={18} />}{busy ? "چاوەڕوانبە…" : "پاشەکەوت و بەردەوامبە"}</button></form>;
}
