"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { KeyRound, LoaderCircle, ShieldCheck } from "lucide-react";

export default function SuperAdminLoginForm() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(null); try { const res = await fetch("/api/admin/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const body = await res.json(); if (!res.ok) throw new Error(body.message || "چوونەژوورەوە سەرنەکەوت."); router.replace(body.mustChangePassword ? "/admin/change-password" : "/admin"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "چوونەژوورەوە سەرنەکەوت."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="w-full max-w-md rounded-[28px] border border-primary/20 bg-card p-6 shadow-[0_24px_70px_var(--shadow-brand)] sm:p-8" dir="rtl"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/12 text-primary"><ShieldCheck size={24} /></div><p className="mt-5 text-xs font-black tracking-[.2em] text-primary">REK ERP</p><h1 className="mt-2 text-3xl font-black">چوونەژورەوە تەنها بۆ ڕەهەند سوپەر ئەدمین ڕێگا پێدراوە</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">ئەم بەشە تەنها بۆ بەڕێوەبەری سیستەمە و بە هەژماری کۆمپانیا ناکرێت بچرێتە ژوورەوە.</p><label className="mt-6 block text-sm font-black">ئیمەیڵ<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-left outline-none focus:border-primary/60" dir="ltr" /></label><label className="mt-4 block text-sm font-black">وشەی نهێنی<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-left outline-none focus:border-primary/60" dir="ltr" /></label>{message ? <p role="status" className="mt-4 rounded-xl bg-destructive/10 px-3 py-2 text-sm text-destructive">{message}</p> : null}<button disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary font-black text-primary-foreground disabled:opacity-60">{busy ? <LoaderCircle className="animate-spin" size={18} /> : <KeyRound size={18} />}{busy ? "چاوەڕوانبە…" : "چوونەژوورەوە"}</button></form>;
}
