"use client";
import { useEffect, useState } from "react";
import { appToast } from "@/lib/toast";
type Release = { id:string; version:string; title:string; summary:string; changes?:string|null; releaseDate:string; publishedAt?:string|null; isCurrent:boolean; isNew:boolean; isRead:boolean };
export default function ReleasesClient() {
 const [items,setItems]=useState<Release[]>([]); const [admin,setAdmin]=useState(false);
 const [form,setForm]=useState({version:"v1.0.0",title:"",releaseDate:new Date().toISOString().slice(0,10),summary:"",changes:"",publishedAt:new Date().toISOString(),isCurrent:true,isActive:true});
 const load=()=>fetch("/api/releases",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(j.success){setItems(j.data);setAdmin(j.admin)}});
 useEffect(()=>{void load()},[]);
 async function read(id:string){const r=await fetch(`/api/releases/${id}/read`,{method:"POST"}); if(!r.ok) appToast.error("نەتوانرا وەشانەکە وەک خوێندراو دیاری بکرێت"); else void load()}
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/releases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!j.success)appToast.error(j.message||"نەتوانرا وەشان دروست بکرێت");else{appToast.success("وەشان بڵاوکرایەوە");void load()}}
 const field="border border-border bg-background px-3 py-2 text-sm";
 return <main className="space-y-5"><header><h1 className="text-3xl font-black text-primary">وەشان</h1><p className="text-sm text-muted-foreground">مێژووی وەشان و گۆڕانکارییە بڵاوکراوەکان{admin ? " · دیمەنی بەڕێوەبەر" : ""}</p></header>{admin&&<form onSubmit={create} className="rek-card grid gap-3 p-4 sm:grid-cols-2"><input required dir="ltr" className={field} value={form.version} onChange={e=>setForm({...form,version:e.target.value})} placeholder="v1.0.0"/><input required className={field} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="ناونیشانی وەشان"/><input required type="date" className={field} value={form.releaseDate} onChange={e=>setForm({...form,releaseDate:e.target.value})}/><input required className={field} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="پوختە"/><textarea className={`${field} sm:col-span-2`} value={form.changes} onChange={e=>setForm({...form,changes:e.target.value})} placeholder="گۆڕانکارییە وردەکان"/><button className="bg-primary px-4 py-2 font-bold text-primary-foreground" type="submit">بڵاوکردنەوەی وەشان</button></form>}<div className="grid gap-4">{items.map(r=><article key={r.id} className="rek-card p-5"><div className="flex flex-wrap items-center gap-2"><b dir="ltr">{r.version}</b>{r.isCurrent&&<span className="bg-primary/10 px-2 py-1 text-xs text-primary">ئێستا</span>}{r.isNew&&<span className="bg-amber-100 px-2 py-1 text-xs text-amber-800">وەشانی نوێ</span>}</div><h2 className="mt-2 text-lg font-black">{r.title}</h2><p className="mt-1 text-sm">{r.summary}</p>{r.changes&&<p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{r.changes}</p>}<time className="mt-3 block text-xs" dateTime={r.releaseDate}>{new Date(r.releaseDate).toLocaleDateString("ckb-IQ")}</time>{!r.isRead&&<button type="button" onClick={()=>void read(r.id)} className="mt-3 bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">وەک خوێندراو</button>}</article>)}</div>{!items.length&&<p className="text-sm text-muted-foreground">هیچ وەشانێکی بڵاوکراوە نییە.</p>}</main>
}
