export const AUDIT_MODULES = [
  "AUTH",
  "PRODUCT",
  "CUSTOMER",
  "SUPPLIER",
  "SALE",
  "PURCHASE",
  "INVOICE",
  "INVENTORY",
  "WAREHOUSE",
  "UNIT",
  "EMPLOYEE",
  "SETTINGS",
  "BARCODE",
  "SYSTEM",
  "DRAFT",
  "DASHBOARD",
  "REPORT",
  "BRAND",
  "CATEGORY",
] as const;

export type AuditModule = (typeof AUDIT_MODULES)[number] | string;

export const AUDIT_ACTIONS = [
  "CREATE",
  "UPDATE",
  "DELETE",
  "RESTORE",
  "LOGIN",
  "LOGOUT",
  "VIEW",
  "EXPORT",
  "IMPORT",
  "PRINT",
  "ADJUST",
  "TRANSFER",
  "UNDO",
  "REDO",
  "BULK",
  "ARCHIVE",
  "AUTOSAVE",
  "DRAFT_RECOVERY",
  "RECOVERY_CREATED",
  "RECOVERY_RESTORED",
  "RECOVERY_DELETED",
  "RECOVERY_EXPIRED",
  "OTHER",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number] | string;

export const AUDIT_MODULE_LABELS: Record<string, string> = {
  AUTH: "Auth",
  PRODUCT: "Products",
  CUSTOMER: "Customers",
  SUPPLIER: "Suppliers",
  SALE: "Sales",
  PURCHASE: "Purchases",
  INVOICE: "Invoices",
  INVENTORY: "Inventory",
  WAREHOUSE: "Warehouses",
  UNIT: "Units",
  EMPLOYEE: "Employees",
  SETTINGS: "Settings",
  BARCODE: "Barcode",
  SYSTEM: "System",
  DRAFT: "Drafts",
  DASHBOARD: "Dashboard",
  REPORT: "Reports",
  BRAND: "Brands",
  CATEGORY: "Categories",
};

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  CREATE: "Create",
  UPDATE: "Update",
  DELETE: "Delete",
  RESTORE: "Restore",
  LOGIN: "Login",
  LOGOUT: "Logout",
  VIEW: "View",
  EXPORT: "Export",
  IMPORT: "Import",
  PRINT: "Print",
  ADJUST: "Adjust",
  TRANSFER: "Transfer",
  UNDO: "Undo",
  REDO: "Redo",
  BULK: "Bulk",
  ARCHIVE: "Archive",
  AUTOSAVE: "Auto Save",
  DRAFT_RECOVERY: "Draft Recovery",
  RECOVERY_CREATED: "Recovery Created",
  RECOVERY_RESTORED: "Recovery Restored",
  RECOVERY_DELETED: "Recovery Deleted",
  RECOVERY_EXPIRED: "Recovery Expired",
  OTHER: "Other",
};

export const AUDIT_STATUS_LABELS: Record<string, string> = {
  success: "Success",
  failed: "Failed",
  pending: "Pending",
  warning: "Warning",
};
