export const AUDIT_MODULES = [
  "AUTH",
  "PRODUCT",
  "CUSTOMER",
  "SUPPLIER",
  "SALE",
  "PURCHASE",
  "INVOICE",
  "INVENTORY",
  "WAREHOUSE",
  "UNIT",
  "EMPLOYEE",
  "SETTINGS",
  "BARCODE",
  "SYSTEM",
  "DRAFT",
  "DASHBOARD",
  "REPORT",
  "BRAND",
  "CATEGORY",
] as const;

export type AuditModule = (typeof AUDIT_MODULES)[number] | string;

export const AUDIT_ACTIONS = [
  "CREATE",
  "UPDATE",
  "DELETE",
  "RESTORE",
  "LOGIN",
  "LOGOUT",
  "VIEW",
  "EXPORT",
  "IMPORT",
  "PRINT",
  "ADJUST",
  "TRANSFER",
  "UNDO",
  "REDO",
  "BULK",
  "ARCHIVE",
  "AUTOSAVE",
  "DRAFT_RECOVERY",
  "RECOVERY_CREATED",
  "RECOVERY_RESTORED",
  "RECOVERY_DELETED",
  "RECOVERY_EXPIRED",
  "OTHER",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number] | string;

export const AUDIT_MODULE_LABELS: Record<string, string> = {
  AUTH: "Auth",
  PRODUCT: "بەرهەمەکان",
  CUSTOMER: "کڕیارەکان",
  SUPPLIER: "دابینکەران",
  SALE: "فرۆشتن",
  PURCHASE: "کڕین",
  INVOICE: "پسوولەکان",
  INVENTORY: "ئینڤێنتۆری",
  WAREHOUSE: "کۆگاکان",
  UNIT: "یەکەکان",
  EMPLOYEE: "کارمەندان",
  SETTINGS: "ڕێکخستنەکان",
  BARCODE: "بارکۆد",
  SYSTEM: "سیستەم",
  DRAFT: "Drafts",
  DASHBOARD: "داشبۆرد",
  REPORT: "ڕاپۆرتەکان",
  BRAND: "براندەکان",
  CATEGORY: "پۆلەکان",
};

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  CREATE: "Create",
  UPDATE: "Update",
  DELETE: "سڕینەوە",
  RESTORE: "گەڕاندنەوە",
  LOGIN: "Login",
  LOGOUT: "چوونەدەرەوە",
  VIEW: "بینین",
  EXPORT: "هەناردەکردن",
  IMPORT: "Import",
  PRINT: "چاپکردن",
  ADJUST: "Adjust",
  TRANSFER: "Transfer",
  UNDO: "پاشگەزبوونەوە",
  REDO: "دووبارەکردنەوە",
  BULK: "Bulk",
  ARCHIVE: "ئەرشیفکردن",
  AUTOSAVE: "پاشەکەوتی خۆکار",
  DRAFT_RECOVERY: "Draft Recovery",
  RECOVERY_CREATED: "Recovery Created",
  RECOVERY_RESTORED: "Recovery Restored",
  RECOVERY_DELETED: "Recovery Deleted",
  RECOVERY_EXPIRED: "Recovery Expired",
  OTHER: "هیتر",
};

export const AUDIT_STATUS_LABELS: Record<string, string> = {
  success: "Success",
  failed: "سەرنەکەوت",
  pending: "Pending",
  warning: "Warning",
};
