import {
  ChartColumnIncreasing,
  FileBarChart,
  History,
  Shield,
} from "lucide-react";
import { defineDocModule } from "@/lib/docs/helpers";

export const insightsModules = [
  defineDocModule({
    slug: "analytics",
    title: "شیکاری",
    shortDescription: "پوختەی داهات، خەرجی، کۆگا و تێڕوانینی بازرگانی.",
    categoryId: "insights",
    icon: ChartColumnIncreasing,
    appRoute: "/dashboard/analytics",
    keywords: ["شیکاری", "چارت", "داهات", "خەرجی", "کۆگا"],
    sections: {
      overview: [
        "شیکاری پوختەی ژمارەیی کارەکەت پیشان دەدات — فرۆشتن، کڕین، کۆگا، قازانج — بە چارت و ئامار.",
      ],
      purpose: ["بینینی گشتی", "بەراوردکردن", "دۆزینەوەی ڕێڕەو"],
      whyExists: ["ژمارە بە تەنها لیست ناتوانێت وەڵام بداتەوە؛ شیکاری وەڵامی «چۆنە؟» دەدات."],
      whenToUse: ["کۆتایی هەفتە/مانگ", "پێش بڕیاردان"],
      steps: ["شیکاری → بەشەکان بگەڕێ → چارت و ئامار بخوێنەوە"],
      workflow: ["فرۆشتن/کڕین → شیکاری → بڕیاردان"],
      bestPractices: ["داتای ڕۆژانە تۆمار بکە بۆ شیکاری دروست"],
      commonMistakes: ["بڕیاردان بەبێ داتای تەواو"],
      tips: ["لەگەڵ ڕاپۆرت بەکاربهێنە"],
      faq: ["ئایا ڕاستەوخۆ نوێ دەبێتەوە؟ — بەپێی داتای تۆمارکراو"],
      troubleshooting: ["چارت بەتاڵ → فرۆشتن/کڕین تۆمار کرا؟"],
      related: ["ڕاپۆرتەکان", "داهات", "خەرجی"],
    },
  }),

  defineDocModule({
    slug: "reports",
    title: "ڕاپۆرتەکان",
    shortDescription: "ڕاپۆرتی وردی فرۆشتن، کڕین، کۆگا و کارمەند.",
    categoryId: "insights",
    icon: FileBarChart,
    appRoute: "/dashboard/reports",
    keywords: ["ڕاپۆرت", "هەناردە", "Excel", "پوختە"],
    sections: {
      overview: ["ڕاپۆرتەکان وردەکاری لیست و کۆی گشتی دەدەن — بۆ چاپ، هەناردە یان پشکنین."],
      purpose: ["وردەکاری", "هەناردە", "بەڵگەی فەرمی"],
      whyExists: ["بۆ ژمێری، بەڕێوەبەر و پشکنینی داتا."],
      whenToUse: ["کۆتایی مانگ", "داواکاری بەڕێوەبەر"],
      steps: ["ڕاپۆرتەکان → جۆر هەڵبژێرە → ماوە → بینین/هەناردە"],
      workflow: ["داتا تۆمار → ڕاپۆرت → هەناردە"],
      bestPractices: ["ماوەی دروست هەڵبژێرە"],
      commonMistakes: ["ماوەی هەڵە"],
      tips: ["هەناردەی Excel بۆ ژمێری"],
      faq: ["جۆرەکانی ڕاپۆرت؟ — فرۆشتن، کڕین، کۆگا، کارمەند"],
      troubleshooting: ["ڕاپۆرت بەتاڵ → داتا لە ماوەکەدا هەیە؟"],
      related: ["شیکاری", "فرۆشتن", "کڕین"],
    },
  }),

  defineDocModule({
    slug: "activity",
    title: "چالاکی",
    shortDescription: "مێژووی کردارەکان و چاودێری کار لە سیستەم.",
    categoryId: "insights",
    icon: History,
    appRoute: "/dashboard/activity",
    keywords: ["چالاکی", "مێژوو", "کردار", "timeline"],
    sections: {
      overview: ["چالاکی تایم‌لاینی کردارە گرنگەکان پیشان دەدات — دروستکردن، دەستکاری، سڕینەوە."],
      purpose: ["چاودێری", "دۆزینەوەی کێ چی کرد"],
      whyExists: ["بۆ شەفافیەت و چارەسەری کێشە."],
      whenToUse: ["کاتێک گۆڕانکاریەک نادروستە", "پشکنینی کار"],
      steps: ["چالاکی → فلتەر → کردارەکان بخوێنەوە"],
      workflow: ["کردار لە سیستەم → چالاکی تۆمار → پشکنین"],
      bestPractices: ["بەردەوام سەیری بکە لە کۆمپانیای گەورە"],
      commonMistakes: ["پشتگوێخستنی چالاکی"],
      tips: ["لەگەڵ تۆماری وردبینی بەکاربهێنە"],
      faq: ["چەند ماوە دەپارێزرێت؟ — بەپێی سیاسەتی کۆمپانیا لە داتابەیس"],
      troubleshooting: ["چالاکی نییە → کردار تۆمار نەبووە؟"],
      related: ["تۆماری وردبینی", "مێژووی وەشان"],
    },
  }),

  defineDocModule({
    slug: "audit-log",
    title: "تۆماری وردبینی",
    shortDescription: "تۆماری فنی وردبینی بۆ پاراستن و پشکنین.",
    categoryId: "insights",
    icon: Shield,
    appRoute: "/dashboard/audit-log",
    keywords: ["وردبینی", "audit", "تۆمار", "پاراستن"],
    sections: {
      overview: [
        "تۆماری وردبینی تۆماری وردتری گۆڕانکارییە — بۆ بەڕێوەبەر و پاراستنی داتا.",
      ],
      purpose: ["پاراستن", "گەڕانەوە بۆ سەرچاوە", "پشکنینی هەڵە"],
      whyExists: ["لە ERPـدا گرنگە بزانیت کێ چی گۆڕیوە."],
      whenToUse: ["کێشەی داتا", "پشکنینی ئاسایش"],
      steps: ["تۆماری وردبینی → گەڕان/فلتەر → وردەکاری"],
      workflow: ["گۆڕانکاری → تۆمار → پشکنین"],
      bestPractices: ["تەنها بەڕێوەبەر بەکاری بهێنێت"],
      commonMistakes: ["پشتگوێخستن"],
      tips: ["لەگەڵ گەڕاندنەوەی وەشان"],
      faq: ["جیاوازی لە چالاکی؟ — وردبینی فنیترە"],
      troubleshooting: ["تۆمار نییە → کردار تۆمارکراو نەبوو"],
      related: ["چالاکی", "پاراستنی زانیاری", "مێژووی وەشان"],
    },
  }),
];
