/** Official Learning Center modules — slug order is the canonical catalog order. */
export const OFFICIAL_DOC_SLUGS = [
  "users",
  "company",
  "profile",
  "dashboard",
  "currency",
  "inventory",
  "products",
  "warehouse",
  "units",
  "barcode",
  "sales",
  "purchases",
  "invoices",
  "customers",
  "suppliers",
  "employees",
  "employee-reports",
  "analytics",
  "reports",
  "activity",
  "audit-log",
  "version-history",
  "ai-assistant",
  "notifications",
  "recent",
  "drafts",
  "recycle-bin",
  "bulk",
  "numbering",
  "data-backup",
  "calculator",
  "settings",
] as const;

export type OfficialDocSlug = (typeof OFFICIAL_DOC_SLUGS)[number];
